# Generated by Django 2.2 on 2019-12-12 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qna_app', '0002_auto_20191212_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='qna_app.CategoryModel'),
            preserve_default=False,
        ),
    ]
